
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Backend.Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int NUMERO = 22;
  public static final int CHAR = 15;
  public static final int NOMBRE = 19;
  public static final int CASE = 45;
  public static final int DOUBLE = 13;
  public static final int RESTA = 33;
  public static final int DOS_PUNTOS = 30;
  public static final int PRIVATE = 10;
  public static final int INT = 12;
  public static final int LLAVE_C = 29;
  public static final int ASTERISCO = 27;
  public static final int FOR = 39;
  public static final int LLAVE_A = 28;
  public static final int IGUAL = 36;
  public static final int CARACTER = 24;
  public static final int OBJECT = 17;
  public static final int CLASS = 3;
  public static final int DIV = 35;
  public static final int IF = 42;
  public static final int THIS = 4;
  public static final int PUNTO_COMA = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int RETURN = 6;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int CADENA = 21;
  public static final int MENOS = 34;
  public static final int BREAK = 7;
  public static final int OPERADOR_LOGICO = 48;
  public static final int VOID = 20;
  public static final int SWITCH = 44;
  public static final int NO = 49;
  public static final int OPERADOR_RELACIONAL = 47;
  public static final int ELSE = 43;
  public static final int PROTECTED = 9;
  public static final int PUNTO = 26;
  public static final int PARENTESIS_C = 38;
  public static final int WHILE = 40;
  public static final int FINAL = 11;
  public static final int PARENTESIS_A = 37;
  public static final int DEFAULT = 46;
  public static final int PUBLIC = 8;
  public static final int IIMPORT = 2;
  public static final int BOOLEANO = 23;
  public static final int STRING = 14;
  public static final int OBJETO = 18;
  public static final int DO = 41;
  public static final int MAS = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IIMPORT",
  "CLASS",
  "THIS",
  "NEW",
  "RETURN",
  "BREAK",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "FINAL",
  "INT",
  "DOUBLE",
  "STRING",
  "CHAR",
  "BOOLEAN",
  "OBJECT",
  "OBJETO",
  "NOMBRE",
  "VOID",
  "CADENA",
  "NUMERO",
  "BOOLEANO",
  "CARACTER",
  "PUNTO_COMA",
  "PUNTO",
  "ASTERISCO",
  "LLAVE_A",
  "LLAVE_C",
  "DOS_PUNTOS",
  "COMA",
  "MAS",
  "RESTA",
  "MENOS",
  "DIV",
  "IGUAL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "FOR",
  "WHILE",
  "DO",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "OPERADOR_RELACIONAL",
  "OPERADOR_LOGICO",
  "NO"
  };

  /* non terminals */
  static final int strings = 47;
  static final int bloque_clase = 7;
  static final int variable_object = 20;
  static final int sentencia_if = 70;
  static final int retorno_variable = 86;
  static final int asignacion_completa_for = 60;
  static final int argumentacion = 66;
  static final int imports = 1;
  static final int condicion = 77;
  static final int variable_boolean = 18;
  static final int sentencia_control = 69;
  static final int cuerpo_estructuras = 82;
  static final int retorno_string = 88;
  static final int casos_normales = 73;
  static final int operacion_unaria = 52;
  static final int def_metodo_tipo = 26;
  static final int cuerpo_metodo_objeto = 32;
  static final int cuerpo_metodo_boolean = 30;
  static final int invocacion = 63;
  static final int def_metodo_void = 33;
  static final int cuerpo_metodo_char = 29;
  static final int caso = 74;
  static final int contenido_numero = 42;
  static final int ciclo_for = 58;
  static final int creacion_variable_string = 13;
  static final int contenido_variable = 41;
  static final int variable_objeto = 22;
  static final int variable_char = 16;
  static final int direccion = 3;
  static final int condiciones_for = 61;
  static final int retorno_compuesto = 85;
  static final int creacion_variable_boolean = 17;
  static final int parametros = 34;
  static final int contenido_object = 50;
  static final int parada = 93;
  static final int cuerpo_switch = 72;
  static final int asignacion = 39;
  static final int cualquier_contenido = 45;
  static final int def_variable = 9;
  static final int retorno = 84;
  static final int negaciones = 81;
  static final int bloque_general = 83;
  static final int cuerpo_def_metodo = 24;
  static final int iimport = 2;
  static final int incremento_for = 62;
  static final int asignacion_for = 59;
  static final int sentencia_switch = 71;
  static final int contenido_bool = 79;
  static final int retorno_char = 89;
  static final int def_tipo_variable = 10;
  static final int argumentos = 67;
  static final int def_clase = 6;
  static final int retorno_numero = 87;
  static final int cuerpo_invocacion_metodo = 65;
  static final int cuerpo_metodo_string = 28;
  static final int def_metodo = 23;
  static final int contenido_condicion = 80;
  static final int caso_default = 75;
  static final int retorno_object = 91;
  static final int contenido_switch = 76;
  static final int retorno_boolean = 90;
  static final int contenido_objeto = 51;
  static final int creacion_variable_numero = 11;
  static final int variable_string = 14;
  static final int inicio = 0;
  static final int sentencias_clase = 8;
  static final int opciones_autoIncreMas = 56;
  static final int creacion_variable_object = 19;
  static final int contenido_boolean = 49;
  static final int argumento = 68;
  static final int sentencias = 38;
  static final int bloque = 37;
  static final int autoincremento = 54;
  static final int opciones_autoincremento = 55;
  static final int opciones_cualquier_contenido = 46;
  static final int def_metodo_constructor = 25;
  static final int tipos_asignacion = 40;
  static final int visibilidad = 4;
  static final int permitidos = 44;
  static final int retorno_objeto = 92;
  static final int ciclo = 57;
  static final int cuerpo_metodo_numero = 27;
  static final int creacion_variable_char = 15;
  static final int opcion_condicion = 78;
  static final int clase = 5;
  static final int cuerpo_metodo_object = 31;
  static final int cuerpo_invocacion_var = 64;
  static final int incremento = 53;
  static final int contenido_string = 43;
  static final int parametro = 35;
  static final int creacion_variable_objeto = 21;
  static final int tipo = 36;
  static final int variable_numero = 12;
  static final int contenido_char = 48;
}

