/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Manejadores.ManejadorAnalisis;
import Backend.Manejadores.ManejadorArchivos;
import Backend.Manejadores.ManejadorInterfaz;
import Backend.Sockets.ClientProcess;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author phily
 */
public class home extends javax.swing.JFrame {    
    private final ClientProcess clientProcess;//Se inicializará hasta que los manejadores de archivos dejen de tener listas vacías...
    private final ManejadorInterfaz manejadorInterfaz = new ManejadorInterfaz();
    private final ManejadorArchivos manejadorArchivos_Proyecto1;
    private final ManejadorArchivos manejadorArchivos_Proyecto2;
    private final ManejadorAnalisis manejadorAnalisis;
    ArrayList<ArrayList<File>> listaArchivos = new ArrayList<>();//esta es para setear las dos listas de los archivos recogidos de cada proyecto...
    String[] arregloPrueba;    
    boolean esJSON;
    
    /**
     * Creates new form home
     */
    public home() {
       this.manejadorInterfaz.cambiarApariencia();
        
       initComponents();
        
       this.manejadorInterfaz.setComponents(scroll_proyecto1, txtA_proyecto1,
               scroll_proyecto2, txtA_proyecto2,
               scroll_txtA_JSON, txt_JSON, 
               scroll_TxtA_Reportes, txtA_Reportes, log_JSON, log_Reportes,
               btn_analizarJSON, btn_analizarReporte, btn_visualizarHTML);       
       this.manejadorArchivos_Proyecto1 = new ManejadorArchivos();
       this.manejadorArchivos_Proyecto2 = new ManejadorArchivos();       
       this.manejadorAnalisis = new ManejadorAnalisis(manejadorInterfaz);
       this.clientProcess = new ClientProcess(this.manejadorInterfaz, manejadorAnalisis); 
       
       area_HTML.setContentType("text/html");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btn_carga1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_carga2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_Carga1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_Carga2 = new javax.swing.JList<>();
        btn_analizar = new javax.swing.JButton();
        scroll_proyecto1 = new javax.swing.JScrollPane();
        txtA_proyecto1 = new javax.swing.JTextArea();
        scroll_proyecto2 = new javax.swing.JScrollPane();
        txtA_proyecto2 = new javax.swing.JTextArea();
        lbl_ubicacion_Proyecto1 = new javax.swing.JLabel();
        lbl_ubicacion_Proyecto2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tab_Cliente = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        scroll_txtA_JSON = new javax.swing.JScrollPane();
        txt_JSON = new javax.swing.JTextArea();
        btn_analizarJSON = new javax.swing.JButton();
        lbl_ubicacion_JSON = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log_JSON = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtF_textoBusqueda_JSON = new javax.swing.JTextField();
        lbl_btn_buscar_JSON = new javax.swing.JLabel();
        lbl_btn_findNext_JSON = new javax.swing.JLabel();
        lbtn_finPrev_JSON = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_analizarReporte = new javax.swing.JButton();
        scroll_TxtA_Reportes = new javax.swing.JScrollPane();
        txtA_Reportes = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        log_Reportes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lbl_ubicacion_Reportes = new javax.swing.JLabel();
        txtF_textoBusqueda_Reportes = new javax.swing.JTextField();
        lbl_btn_buscar_Reportes = new javax.swing.JLabel();
        lbl_btn_findNext_Reportes = new javax.swing.JLabel();
        btn_visualizarHTML = new javax.swing.JButton();
        lbtn_finPrev_Reporte = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        area_HTML = new javax.swing.JEditorPane();
        lbl_guardarProyecto = new javax.swing.JLabel();
        lbl_btn_abrirProyecto = new javax.swing.JLabel();
        lbl_guardarCambios = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_carga1.setFont(new java.awt.Font("Manjari", 0, 14)); // NOI18N
        btn_carga1.setText("Proyecto 1");
        btn_carga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carga1ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_carga2.setFont(new java.awt.Font("Manjari", 0, 14)); // NOI18N
        btn_carga2.setText("Proyecto 2");
        btn_carga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carga2ActionPerformed(evt);
            }
        });

        lista_Carga1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lista_Carga1.setFont(new java.awt.Font("Lato Medium", 0, 14)); // NOI18N
        lista_Carga1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_Carga1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lista_Carga1);

        lista_Carga2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lista_Carga2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_Carga2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lista_Carga2);

        btn_analizar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        btn_analizar.setText("Analizar");
        btn_analizar.setEnabled(false);
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        txtA_proyecto1.setEditable(false);
        txtA_proyecto1.setColumns(20);
        txtA_proyecto1.setRows(5);
        txtA_proyecto1.setTabSize(5);
        txtA_proyecto1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtA_proyecto1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtA_proyecto1CaretUpdate(evt);
            }
        });
        scroll_proyecto1.setViewportView(txtA_proyecto1);

        txtA_proyecto2.setEditable(false);
        txtA_proyecto2.setColumns(20);
        txtA_proyecto2.setRows(5);
        txtA_proyecto2.setTabSize(5);
        txtA_proyecto2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtA_proyecto2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtA_proyecto2CaretUpdate(evt);
            }
        });
        scroll_proyecto2.setViewportView(txtA_proyecto2);

        lbl_ubicacion_Proyecto1.setBackground(new java.awt.Color(206, 214, 228));
        lbl_ubicacion_Proyecto1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ubicacion_Proyecto1.setText("linea: 0    columna: 0  ");
        lbl_ubicacion_Proyecto1.setOpaque(true);

        lbl_ubicacion_Proyecto2.setBackground(new java.awt.Color(206, 214, 228));
        lbl_ubicacion_Proyecto2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ubicacion_Proyecto2.setText("linea: 0    columna: 0  ");
        lbl_ubicacion_Proyecto2.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_analizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(btn_carga1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_carga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scroll_proyecto1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                            .addComponent(lbl_ubicacion_Proyecto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scroll_proyecto2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ubicacion_Proyecto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(scroll_proyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ubicacion_Proyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(scroll_proyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lbl_ubicacion_Proyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_carga1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_carga2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cargar Proyectos", jPanel3);

        tab_Cliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_ClienteStateChanged(evt);
            }
        });

        txt_JSON.setColumns(20);
        txt_JSON.setRows(5);
        txt_JSON.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_JSON.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_JSONCaretUpdate(evt);
            }
        });
        scroll_txtA_JSON.setViewportView(txt_JSON);

        btn_analizarJSON.setText("Analizar JSON");
        btn_analizarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarJSONActionPerformed(evt);
            }
        });

        lbl_ubicacion_JSON.setBackground(new java.awt.Color(229, 233, 239));
        lbl_ubicacion_JSON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ubicacion_JSON.setText("línea: 0    columna: 0");
        lbl_ubicacion_JSON.setOpaque(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        log_JSON.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Linea", "Columna", "Tipo", "Error", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(log_JSON);
        if (log_JSON.getColumnModel().getColumnCount() > 0) {
            log_JSON.getColumnModel().getColumn(0).setMinWidth(50);
            log_JSON.getColumnModel().getColumn(0).setPreferredWidth(50);
            log_JSON.getColumnModel().getColumn(0).setMaxWidth(50);
            log_JSON.getColumnModel().getColumn(1).setMinWidth(55);
            log_JSON.getColumnModel().getColumn(1).setPreferredWidth(55);
            log_JSON.getColumnModel().getColumn(1).setMaxWidth(55);
            log_JSON.getColumnModel().getColumn(2).setMinWidth(55);
            log_JSON.getColumnModel().getColumn(2).setPreferredWidth(55);
            log_JSON.getColumnModel().getColumn(2).setMaxWidth(55);
            log_JSON.getColumnModel().getColumn(3).setMinWidth(93);
            log_JSON.getColumnModel().getColumn(3).setPreferredWidth(93);
            log_JSON.getColumnModel().getColumn(3).setMaxWidth(93);
            log_JSON.getColumnModel().getColumn(4).setMinWidth(115);
            log_JSON.getColumnModel().getColumn(4).setPreferredWidth(115);
            log_JSON.getColumnModel().getColumn(4).setMaxWidth(115);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("LOG");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_btn_buscar_JSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa-icon.png"))); // NOI18N
        lbl_btn_buscar_JSON.setText("Buscar: ");
        lbl_btn_buscar_JSON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_buscar_JSONMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_btn_buscar_JSONMousePressed(evt);
            }
        });

        lbl_btn_findNext_JSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_next.png"))); // NOI18N
        lbl_btn_findNext_JSON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_findNext_JSON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_findNext_JSONMouseClicked(evt);
            }
        });

        lbtn_finPrev_JSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boton_prev.png"))); // NOI18N
        lbtn_finPrev_JSON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbtn_finPrev_JSON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtn_finPrev_JSONMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll_txtA_JSON)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_analizarJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lbl_btn_buscar_JSON, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtF_textoBusqueda_JSON, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbtn_finPrev_JSON)
                        .addGap(16, 16, 16)
                        .addComponent(lbl_btn_findNext_JSON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ubicacion_JSON, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(scroll_txtA_JSON, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_analizarJSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_btn_buscar_JSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_ubicacion_JSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_btn_findNext_JSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtF_textoBusqueda_JSON)
                            .addComponent(lbtn_finPrev_JSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab_Cliente.addTab("JSON", jPanel5);

        btn_analizarReporte.setText("Analizar Reporte");
        btn_analizarReporte.setEnabled(false);
        btn_analizarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarReporteActionPerformed(evt);
            }
        });

        txtA_Reportes.setEditable(false);
        txtA_Reportes.setColumns(20);
        txtA_Reportes.setRows(5);
        txtA_Reportes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtA_Reportes.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtA_ReportesCaretUpdate(evt);
            }
        });
        scroll_TxtA_Reportes.setViewportView(txtA_Reportes);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        log_Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Linea", "Columna", "Tipo", "Error", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(log_Reportes);
        if (log_Reportes.getColumnModel().getColumnCount() > 0) {
            log_Reportes.getColumnModel().getColumn(0).setMinWidth(50);
            log_Reportes.getColumnModel().getColumn(0).setPreferredWidth(50);
            log_Reportes.getColumnModel().getColumn(0).setMaxWidth(50);
            log_Reportes.getColumnModel().getColumn(1).setMinWidth(55);
            log_Reportes.getColumnModel().getColumn(1).setPreferredWidth(55);
            log_Reportes.getColumnModel().getColumn(1).setMaxWidth(55);
            log_Reportes.getColumnModel().getColumn(2).setMinWidth(55);
            log_Reportes.getColumnModel().getColumn(2).setPreferredWidth(55);
            log_Reportes.getColumnModel().getColumn(2).setMaxWidth(55);
            log_Reportes.getColumnModel().getColumn(3).setMinWidth(97);
            log_Reportes.getColumnModel().getColumn(3).setPreferredWidth(97);
            log_Reportes.getColumnModel().getColumn(3).setMaxWidth(97);
            log_Reportes.getColumnModel().getColumn(4).setMinWidth(115);
            log_Reportes.getColumnModel().getColumn(4).setPreferredWidth(115);
            log_Reportes.getColumnModel().getColumn(4).setMaxWidth(115);
        }

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("LOG");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_ubicacion_Reportes.setBackground(new java.awt.Color(229, 233, 239));
        lbl_ubicacion_Reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ubicacion_Reportes.setText("línea: 0    columna: 0");
        lbl_ubicacion_Reportes.setOpaque(true);

        txtF_textoBusqueda_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_textoBusqueda_ReportesActionPerformed(evt);
            }
        });

        lbl_btn_buscar_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa-icon.png"))); // NOI18N
        lbl_btn_buscar_Reportes.setText("Buscar: ");
        lbl_btn_buscar_Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_buscar_ReportesMouseClicked(evt);
            }
        });

        lbl_btn_findNext_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_next.png"))); // NOI18N
        lbl_btn_findNext_Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_findNext_Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_findNext_ReportesMouseClicked(evt);
            }
        });

        btn_visualizarHTML.setText("Visualizar HTML");
        btn_visualizarHTML.setEnabled(false);
        btn_visualizarHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_visualizarHTMLActionPerformed(evt);
            }
        });

        lbtn_finPrev_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boton_prev.png"))); // NOI18N
        lbtn_finPrev_Reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbtn_finPrev_Reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtn_finPrev_ReporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_TxtA_Reportes)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_analizarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_visualizarHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_btn_buscar_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtF_textoBusqueda_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbtn_finPrev_Reporte)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_btn_findNext_Reportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ubicacion_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(scroll_TxtA_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_analizarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_btn_buscar_Reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtF_textoBusqueda_Reportes)
                        .addComponent(btn_visualizarHTML))
                    .addComponent(lbl_btn_findNext_Reportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ubicacion_Reportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbtn_finPrev_Reporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab_Cliente.addTab("Reportes", jPanel6);

        jScrollPane5.setViewportView(area_HTML);

        tab_Cliente.addTab("Reporte Generado", jScrollPane5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_Cliente, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_Cliente))
        );

        jTabbedPane1.addTab("Resultados", jPanel4);

        lbl_guardarProyecto.setFont(new java.awt.Font("Manjari", 0, 16)); // NOI18N
        lbl_guardarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar_icon_3.png"))); // NOI18N
        lbl_guardarProyecto.setText("  Guardar Proyecto");
        lbl_guardarProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_guardarProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_guardarProyectoMouseClicked(evt);
            }
        });

        lbl_btn_abrirProyecto.setFont(new java.awt.Font("Manjari", 0, 16)); // NOI18N
        lbl_btn_abrirProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open_icon.png"))); // NOI18N
        lbl_btn_abrirProyecto.setText("  Abrir");
        lbl_btn_abrirProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_abrirProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_abrirProyectoMouseClicked(evt);
            }
        });

        lbl_guardarCambios.setFont(new java.awt.Font("Manjari", 0, 16)); // NOI18N
        lbl_guardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar_Cambios.png"))); // NOI18N
        lbl_guardarCambios.setText("  Guardar Cambios");
        lbl_guardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_guardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_guardarCambiosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_abrirProyecto)
                .addGap(30, 30, 30)
                .addComponent(lbl_guardarProyecto)
                .addGap(26, 26, 26)
                .addComponent(lbl_guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_btn_abrirProyecto)
                    .addComponent(lbl_guardarProyecto)
                    .addComponent(lbl_guardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        jMenuBar1.setBackground(new java.awt.Color(87, 97, 111));
        jMenuBar1.setForeground(new java.awt.Color(201, 214, 228));

        jMenu1.setForeground(new java.awt.Color(194, 205, 216));
        jMenu1.setText("Options |");
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(194, 205, 216));
        jMenu2.setText("User Manual |");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analizarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarReporteActionPerformed
        if(!txtA_Reportes.getText().isBlank()){
            this.manejadorAnalisis.procesarCOPYRecibido(txtA_Reportes.getText());
        }
    }//GEN-LAST:event_btn_analizarReporteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
        if(this.manejadorArchivos_Proyecto1.getFiles() != null && this.manejadorArchivos_Proyecto2.getFiles() != null){
            listaArchivos.clear();//no creo que provoque problemas si está vacía cuando se invoque esto...
            listaArchivos.add(manejadorArchivos_Proyecto1.getFiles());
            listaArchivos.add(manejadorArchivos_Proyecto2.getFiles());
            this.clientProcess.request(listaArchivos);
        }
    }//GEN-LAST:event_btn_analizarActionPerformed

    private void btn_carga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carga2ActionPerformed
        this.manejadorArchivos_Proyecto2.setFiles();
                
        this.manejadorInterfaz.addArchivosALista(lista_Carga2, this.manejadorArchivos_Proyecto2.getNombreArchivos(), txtA_proyecto2);
        this.enabledMainButton(this.manejadorArchivos_Proyecto1.getFiles(), this.manejadorArchivos_Proyecto2.getFiles());
    }//GEN-LAST:event_btn_carga2ActionPerformed

    private void btn_carga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carga1ActionPerformed
        this.manejadorArchivos_Proyecto1.setFiles();
        
        System.out.println(this.manejadorArchivos_Proyecto1.getNombreArchivos());
        this.manejadorInterfaz.addArchivosALista(lista_Carga1, this.manejadorArchivos_Proyecto1.getNombreArchivos(), txtA_proyecto1);
        this.enabledMainButton(this.manejadorArchivos_Proyecto1.getFiles(), this.manejadorArchivos_Proyecto2.getFiles());
    }//GEN-LAST:event_btn_carga1ActionPerformed

    private void txtA_proyecto1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtA_proyecto1CaretUpdate
       this.manejadorInterfaz.addUbicacion(txtA_proyecto1, lbl_ubicacion_Proyecto1);
    }//GEN-LAST:event_txtA_proyecto1CaretUpdate

    private void txtA_proyecto2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtA_proyecto2CaretUpdate
       this.manejadorInterfaz.addUbicacion(txtA_proyecto2, lbl_ubicacion_Proyecto2);
    }//GEN-LAST:event_txtA_proyecto2CaretUpdate

    private void txt_JSONCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_JSONCaretUpdate
        this.manejadorInterfaz.addUbicacion(txt_JSON, lbl_ubicacion_JSON);
    }//GEN-LAST:event_txt_JSONCaretUpdate

    private void txtA_ReportesCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtA_ReportesCaretUpdate
        this.manejadorInterfaz.addUbicacion(txtA_Reportes, lbl_ubicacion_Reportes);
    }//GEN-LAST:event_txtA_ReportesCaretUpdate

    private void lista_Carga1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_Carga1MouseClicked
        if(this.lista_Carga1.getSelectedIndex()!= -1){
            this.txtA_proyecto1.setText(this.manejadorArchivos_Proyecto1.getFileAsString(this.lista_Carga1.getSelectedIndex()));
        }        
    }//GEN-LAST:event_lista_Carga1MouseClicked

    private void lista_Carga2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_Carga2MouseClicked
        if(this.lista_Carga2.getSelectedIndex()!= -1){
            this.txtA_proyecto2.setText(this.manejadorArchivos_Proyecto2.getFileAsString(this.lista_Carga2.getSelectedIndex()));
        }        
    }//GEN-LAST:event_lista_Carga2MouseClicked

    private void txtF_textoBusqueda_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_textoBusqueda_ReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_textoBusqueda_ReportesActionPerformed

    private void lbl_btn_buscar_JSONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_buscar_JSONMouseClicked
        if(!txt_JSON.getText().isBlank() && !txt_JSON.getText().isEmpty()){
            this.manejadorInterfaz.buscarTexto(txt_JSON, txt_JSON.getText(), txtF_textoBusqueda_JSON.getText(), 0, true);
        }        
    }//GEN-LAST:event_lbl_btn_buscar_JSONMouseClicked

    private void lbl_btn_findNext_JSONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_findNext_JSONMouseClicked
        if(!txt_JSON.getText().isBlank() && !txt_JSON.getText().isEmpty()){
            this.manejadorInterfaz.buscarSiguiente(txt_JSON, txtF_textoBusqueda_JSON.getText());
        }               
    }//GEN-LAST:event_lbl_btn_findNext_JSONMouseClicked

    private void lbl_btn_buscar_JSONMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_buscar_JSONMousePressed
        
    }//GEN-LAST:event_lbl_btn_buscar_JSONMousePressed

    private void lbl_btn_buscar_ReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_buscar_ReportesMouseClicked
        if(!txtA_Reportes.getText().isBlank() && !txtA_Reportes.getText().isEmpty()){
            this.manejadorInterfaz.buscarTexto(txtA_Reportes, txtA_Reportes.getText(), txtF_textoBusqueda_Reportes.getText(), 0, true);
        }        
    }//GEN-LAST:event_lbl_btn_buscar_ReportesMouseClicked

    private void lbl_btn_findNext_ReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_findNext_ReportesMouseClicked
        if(!txtA_Reportes.getText().isBlank() && !txtA_Reportes.getText().isEmpty()){
            this.manejadorInterfaz.buscarSiguiente(txtA_Reportes, txtF_textoBusqueda_Reportes.getText());
        }               
    }//GEN-LAST:event_lbl_btn_findNext_ReportesMouseClicked

    private void btn_analizarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarJSONActionPerformed
        if(!txt_JSON.getText().isBlank() && !txt_JSON.getText().isEmpty()){
            if(this.manejadorAnalisis.verificarEstructuraJSON(txt_JSON.getText())){
                if(this.manejadorAnalisis.getManejadorProyectos().actualProyectIsSaved()){
                    this.manejadorAnalisis.getManejadorProyectos().guardarCambios(txt_JSON.getText(), true);
                }//si no está correcto no se guardará automáticamente PERO el usuario si lo desea podrá hacerlo...                
            }
        }//Esto de forma eqq tendrás que hacer para cuando analices el HTML...
    }//GEN-LAST:event_btn_analizarJSONActionPerformed

    private void lbl_btn_abrirProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_abrirProyectoMouseClicked
        this.manejadorAnalisis.getManejadorProyectos().openProyect();
        
        if(this.manejadorAnalisis.getManejadorProyectos().seCargaronLosArchivos()){
            this.manejadorAnalisis.procesarJSONRecibido(this.manejadorAnalisis.getManejadorProyectos().getProyectoAbierto().getJSON().getContenido(), true);        
            this.manejadorAnalisis.procesarCOPYRecibido(this.manejadorAnalisis.getManejadorProyectos().getProyectoAbierto().getCOPY().getContenido());
                
            this.txt_JSON.setText(this.manejadorAnalisis.getManejadorProyectos().getProyectoAbierto().getJSON().getContenido());
            this.txtA_Reportes.setText(this.manejadorAnalisis.getManejadorProyectos().getProyectoAbierto().getCOPY().getContenido());
        }        
    }//GEN-LAST:event_lbl_btn_abrirProyectoMouseClicked

    private void lbl_guardarProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_guardarProyectoMouseClicked
        this.manejadorAnalisis.getManejadorProyectos().guardarComo(txt_JSON.getText(), txtA_Reportes.getText());
    }//GEN-LAST:event_lbl_guardarProyectoMouseClicked

    private void lbl_guardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_guardarCambiosMouseClicked
        //esto sin importar que el txtA tenga o no contenido, simplemente guarda porque el usuario dice que guardes xD
        if(this.manejadorAnalisis.getManejadorProyectos().actualProyectIsSaved()){                       
            this.manejadorAnalisis.getManejadorProyectos().guardarCambios((esJSON)?txt_JSON.getText():txtA_Reportes.getText(), esJSON);//esto lo averiguaremos dependiendo de que ventana del tabLayer esté enfocada...
        }else{
            this.manejadorAnalisis.getManejadorProyectos().guardarComo(txt_JSON.getText(), txtA_Reportes.getText());
        }
    }//GEN-LAST:event_lbl_guardarCambiosMouseClicked

    private void btn_visualizarHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_visualizarHTMLActionPerformed
        if(this.manejadorAnalisis.getHTML() != null){
            //this.generadorReporte(this.manejadorAnalisis.getHTML());
        }else{
            JOptionPane.showMessageDialog(null, "Copy con errores", "No podrás visualizar "
                 + "el Reporte a\nmenos que arregles los errores",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_visualizarHTMLActionPerformed

    private void tab_ClienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_ClienteStateChanged
        esJSON = (tab_Cliente.getSelectedIndex() == 0);//puesto que este solo cambia cunado lo seleccionan y no cuando pierde o gana el foco, entonces nice xD, nunca dará -1 xD xD bueno eso probé y salió así, de todos modos ahí te fijas de la consola...
        System.out.println(tab_Cliente.getSelectedIndex());
    }//GEN-LAST:event_tab_ClienteStateChanged

    private void lbtn_finPrev_ReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtn_finPrev_ReporteMouseClicked
        if(!txtA_Reportes.getText().isBlank() && !txtA_Reportes.getText().isEmpty()){
            this.manejadorInterfaz.buscarAnterior(txtA_Reportes, txtF_textoBusqueda_Reportes.getText());
        }         
    }//GEN-LAST:event_lbtn_finPrev_ReporteMouseClicked

    private void lbtn_finPrev_JSONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtn_finPrev_JSONMouseClicked
        if(!txt_JSON.getText().isBlank() && !txt_JSON.getText().isEmpty()){
            this.manejadorInterfaz.buscarAnterior(txt_JSON, txtF_textoBusqueda_JSON.getText());
        }         
    }//GEN-LAST:event_lbtn_finPrev_JSONMouseClicked

    private void enabledMainButton(ArrayList<File> archivosProyecto1, ArrayList<File> archivosProyecto2){        
        this.btn_analizar.setEnabled((!archivosProyecto1.isEmpty() && !archivosProyecto2.isEmpty()));        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane area_HTML;
    private javax.swing.JButton btn_analizar;
    private javax.swing.JButton btn_analizarJSON;
    private javax.swing.JButton btn_analizarReporte;
    private javax.swing.JButton btn_carga1;
    private javax.swing.JButton btn_carga2;
    private javax.swing.JButton btn_visualizarHTML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_btn_abrirProyecto;
    private javax.swing.JLabel lbl_btn_buscar_JSON;
    private javax.swing.JLabel lbl_btn_buscar_Reportes;
    private javax.swing.JLabel lbl_btn_findNext_JSON;
    private javax.swing.JLabel lbl_btn_findNext_Reportes;
    private javax.swing.JLabel lbl_guardarCambios;
    private javax.swing.JLabel lbl_guardarProyecto;
    private javax.swing.JLabel lbl_ubicacion_JSON;
    private javax.swing.JLabel lbl_ubicacion_Proyecto1;
    private javax.swing.JLabel lbl_ubicacion_Proyecto2;
    private javax.swing.JLabel lbl_ubicacion_Reportes;
    private javax.swing.JLabel lbtn_finPrev_JSON;
    private javax.swing.JLabel lbtn_finPrev_Reporte;
    private javax.swing.JList<String> lista_Carga1;
    private javax.swing.JList<String> lista_Carga2;
    private javax.swing.JTable log_JSON;
    private javax.swing.JTable log_Reportes;
    private javax.swing.JScrollPane scroll_TxtA_Reportes;
    private javax.swing.JScrollPane scroll_proyecto1;
    private javax.swing.JScrollPane scroll_proyecto2;
    private javax.swing.JScrollPane scroll_txtA_JSON;
    private javax.swing.JTabbedPane tab_Cliente;
    private javax.swing.JTextArea txtA_Reportes;
    private javax.swing.JTextArea txtA_proyecto1;
    private javax.swing.JTextArea txtA_proyecto2;
    private javax.swing.JTextField txtF_textoBusqueda_JSON;
    private javax.swing.JTextField txtF_textoBusqueda_Reportes;
    private javax.swing.JTextArea txt_JSON;
    // End of variables declaration//GEN-END:variables
}
