
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Backend.Analizadores;

/** CUP generated class containing symbol constants. */
public class DEF_ParserSym {
  /* terminals */
  public static final int MENOS = 23;
  public static final int PUNTO = 18;
  public static final int CADENA = 29;
  public static final int IGUAL = 15;
  public static final int METODOS = 11;
  public static final int VARIABLE = 30;
  public static final int SCORE = 5;
  public static final int POR = 24;
  public static final int TIPO = 9;
  public static final int STRING = 3;
  public static final int VARIABLES = 8;
  public static final int COMA = 16;
  public static final int COMENTARIOS = 13;
  public static final int NOMBRE = 7;
  public static final int EOF = 0;
  public static final int PARAMETROS = 12;
  public static final int DIV = 25;
  public static final int TEXTO = 14;
  public static final int PARENTESIS_C = 27;
  public static final int error = 1;
  public static final int PARENTESIS_A = 26;
  public static final int CLASES = 6;
  public static final int PUNTO_COMA = 17;
  public static final int INTEGER = 2;
  public static final int ENTERO = 28;
  public static final int CORCHETE_C = 20;
  public static final int CORCHETE_A = 19;
  public static final int MAS = 21;
  public static final int RESULT = 4;
  public static final int RESTA = 22;
  public static final int FUNCION = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "STRING",
  "RESULT",
  "SCORE",
  "CLASES",
  "NOMBRE",
  "VARIABLES",
  "TIPO",
  "FUNCION",
  "METODOS",
  "PARAMETROS",
  "COMENTARIOS",
  "TEXTO",
  "IGUAL",
  "COMA",
  "PUNTO_COMA",
  "PUNTO",
  "CORCHETE_A",
  "CORCHETE_C",
  "MAS",
  "RESTA",
  "MENOS",
  "POR",
  "DIV",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "ENTERO",
  "CADENA",
  "VARIABLE"
  };
}

