
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Backend.Analizadores;

/** CUP generated class containing symbol constants. */
public class HTML_ParserSym {
  /* terminals */
  public static final int H2_C = 7;
  public static final int PARAMETROS = 36;
  public static final int FOR_C = 17;
  public static final int H2_A = 6;
  public static final int TIPO = 33;
  public static final int FOR_A = 18;
  public static final int NOMBRE = 31;
  public static final int ENTERO = 26;
  public static final int FUNCION = 34;
  public static final int SCORE = 29;
  public static final int H1_C = 5;
  public static final int DOS_PUNTOS = 41;
  public static final int COMENTARIOS = 37;
  public static final int TABLE_C = 9;
  public static final int H1_A = 4;
  public static final int CORCHETE_C = 23;
  public static final int TABLE_A = 8;
  public static final int CORCHETE_A = 22;
  public static final int ITERADOR = 39;
  public static final int HTML_C = 3;
  public static final int HASTA = 40;
  public static final int HTML_A = 2;
  public static final int TR_C = 11;
  public static final int TR_A = 10;
  public static final int CLASES = 30;
  public static final int TH_C = 13;
  public static final int TH_A = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FOR_CA = 19;
  public static final int BR = 16;
  public static final int METODOS = 35;
  public static final int VARIABLES = 32;
  public static final int PUNTO = 24;
  public static final int VARIABLE = 25;
  public static final int TEXTO = 38;
  public static final int TD_C = 15;
  public static final int TD_A = 14;
  public static final int CONTENIDO = 27;
  public static final int VAR_C = 21;
  public static final int VAR_A = 20;
  public static final int RESULT = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML_A",
  "HTML_C",
  "H1_A",
  "H1_C",
  "H2_A",
  "H2_C",
  "TABLE_A",
  "TABLE_C",
  "TR_A",
  "TR_C",
  "TH_A",
  "TH_C",
  "TD_A",
  "TD_C",
  "BR",
  "FOR_C",
  "FOR_A",
  "FOR_CA",
  "VAR_A",
  "VAR_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "PUNTO",
  "VARIABLE",
  "ENTERO",
  "CONTENIDO",
  "RESULT",
  "SCORE",
  "CLASES",
  "NOMBRE",
  "VARIABLES",
  "TIPO",
  "FUNCION",
  "METODOS",
  "PARAMETROS",
  "COMENTARIOS",
  "TEXTO",
  "ITERADOR",
  "HASTA",
  "DOS_PUNTOS"
  };
}

