/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backend.Objetos.Enums;

/**
 *
 * @author phily
 */

public enum SintaxError{
    FATAL_ERROR,
    PARSER_EXPECTED,
    IMPORT_SECTION_WITH_ERRORS, 
    IMPORT_MALFORMED,
    BAD_CLASS_STRUCT,
    BAD_VARIABLE_CREATION, 
    BAD_NUMBER_VAR_CREATION,
    BAD_STRING_VAR_CREATION, 
    BAD_CHAR_VAR_CREATION,
    BAD_BOOLEAN_VAR_CREATION,
    BAD_OBJECT_VAR_CREATION,
    BAD_CUSTOM_OBJECT_VAR_CREATION,
    BAD_METHOD_DECLARATION,
    BAD_NUMBER_METHOD_DECLARATION,
    BAD_STRING_METHOD_DECLARATION,
    BAD_CHAR_METHOD_DECLARATION,
    BAD_BOOLEAN_METHOD_DECLARATION,
    BAD_OBJECT_METHOD_DECLARATION,
    BAD_OBJETO_METHOD_DECLARATION,
    BAD_VOID_METHOD_DECLARATION,
    BAD_PARAM_LIST, 
    BAD_ASSGINED_CONTENT, 
    BAD_AUTINCREMENT_CONTENT,
    BAD_LOOP_STRUCT, 
    BAD_FOR_ASSIGNATION,
    BAD_FOR_CONDITION,
    BAD_FOR_INCREMENT,
    BAD_VAR_INVOCATION,
    ARGUMENTS_SECTION_WITH_ERRORS,
    BAD_TYPE_TO_EVALUATE_ON_SWITCH,
    BAD_SWITCHs_BODY,
    BAD_CASE_LIST,
    BAD_BODY_STRUCT;
}
    

